#pessoa = input("Qual o seu nome ?: ")
#print("Boa noite", pessoa)
#idade = input("Qual a sua idade? ")
#print(idade,"anos")
#enderecoeletronico = input("Qual o seu e-mail ?:")
#print(enderecoeletronico)

numero = input("Digite um número: ")
outroNumero = input("Digite outro número: ")
print("A soma dos números é: ", float(numero) + float(outroNumero))